version: "3"
services:
  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydata"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysqldata:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "4000:8080"
volumes:
  mysqldata:
